router:
  image: registry.service.opg.digital/opguk/nginx-router
  ports:
    - 80:80
    - 443:443
  links:
    - kibana
    - grafana
    - graphite
    - uchiwa
    - example
  environment:
    - OPG_NGINX_ROUTER_00_VHOST=kibana.*
    - OPG_NGINX_ROUTER_00_TARGET=http://kibana:5601
    - OPG_NGINX_ROUTER_01_VHOST=grafana.*
    - OPG_NGINX_ROUTER_01_TARGET=http://grafana:3000
    - OPG_NGINX_ROUTER_02_VHOST=graphite.*
    - OPG_NGINX_ROUTER_02_TARGET=http://graphite
    - OPG_NGINX_ROUTER_03_VHOST=sensu.*
    - OPG_NGINX_ROUTER_03_TARGET=http://uchiwa:3000
    - OPG_NGINX_ROUTER_APP_VHOST=example.*
    - OPG_NGINX_ROUTER_APP_TARGET=http://example


kibana:
  image: registry.service.opg.digital/opguk/kibana
  environment:
    ELASTICSEARCH: elasticsearch
    ELASTICSEARCH_PORT_9200_TCP: 9200
  ports:
    - 8001:5601
  links:
    - elasticsearch
  env_file: ./env

elasticsearchshareddata:
  image: registry.service.opg.digital/opguk/elasticsearch-shared-data

# data on volume
elasticsearch:
  image: registry.service.opg.digital/opguk/elasticsearch
  ports:
    - 9201:9200
    - 9301:9300
  env_file: ./env
  volumes:
    - /tmp/elasticsearchshareddata
  volumes_from:
    - elasticsearchshareddata

# user/pass: admin/admin
grafana:
  image: registry.service.opg.digital/opguk/grafana
  ports:
    - 8002:3000
  links:
    - graphite
  env_file: ./env


logstash:
  image: registry.service.opg.digital/opguk/logstash
  links:
    - redis
    - elasticsearch
    - graphite
  env_file: ./env


redis:
  image: redis
  ports:
    - 6379:6379
  env_file: ./env


# data on volume
graphite:
  image: registry.service.opg.digital/opguk/graphite-statsd
  ports:
    - 8003:80
    - 2003:2003
    - 2003:2003/udp
    - 8125:8125/udp
  env_file: ./env


rabbitmq:
  image: registry.service.opg.digital/opguk/rabbitmq
  ports:
    - 5672:5672
  env_file: ./env


sensuserver:
#  build: sensu-server
  image: registry.service.opg.digital/opguk/sensu-server
  links:
    - redis
    - rabbitmq
    - sensuapi
  env_file: ./env


sensuapi:
#  build: sensu-api
  image: registry.service.opg.digital/opguk/sensu-api
  links:
    - redis
    - rabbitmq
  env_file: ./env


sensuclient:
  image: registry.service.opg.digital/opguk/sensu-client
  ports:
    - 3030:3030
  links:
    - redis
    - rabbitmq
    - graphite
  env_file: ./env


uchiwa:
  image: registry.service.opg.digital/opguk/uchiwa
  links:
    - sensuapi
    - sensuserver
  ports:
    - 8004:3000
  env_file: ./env


monitoringproxy:
  image: registry.service.opg.digital/opguk/monitoring-proxy
  links:
    - redis
    - graphite
  environment:
    MONITORING_REDIS_HOST: redis:6379/0
    MONITORING_GRAPHITE: graphite
    MONITORING_NAMESPACE: myapp.prod
  env_file: ./env


# example app feeding logs to the monitoring stack
example:
  image: registry.service.opg.digital/opguk/nginx
  links:
    - monitoringproxy:monitoring
  ports:
    - 8000:80
  env_file: ./env



#example collectd feeder
#collectd:
#  build: collectd
#  links:
#    - monitoringproxy:monitoring
#  env_file: ./env
