router:
  image: registry.service.dsd.io/opguk/nginx-router:latest
  ports:
    - 80:80
    - 443:443
  links:
    - kibana
    - grafana
    - graphite
    - uchiwa
  environment:
    - OPG_NGINX_ROUTER_00_VHOST=kibana.*
    - OPG_NGINX_ROUTER_00_TARGET=http://kibana
    - OPG_NGINX_ROUTER_01_VHOST=grafana.*
    - OPG_NGINX_ROUTER_01_TARGET=http://grafana
    - OPG_NGINX_ROUTER_02_VHOST=graphite.*
    - OPG_NGINX_ROUTER_02_TARGET=http://graphite
    - OPG_NGINX_ROUTER_03_VHOST=sensu.*
    - OPG_NGINX_ROUTER_03_TARGET=http://uchiwa


kibana:
  image: registry.service.dsd.io/opguk/kibana:latest
  environment:
    ELASTICSEARCH: elasticsearch
    ELASTICSEARCH_PORT_9200_TCP: 9200
  ports:
    - 8001:5601
  links:
    - elasticsearch
  env_file: ./env


# data on volume
elasticsearch:
  image: registry.service.dsd.io/opguk/elasticsearch:latest
  ports:
    - 9201:9200
    - 9301:9300
  env_file: ./env


# user/pass: admin/admin
grafana:
  image: registry.service.dsd.io/opguk/grafana:latest
  ports:
    - 8002:3000
  links:
    - graphite
  env_file: ./env


logstash:
  image: registry.service.dsd.io/opguk/logstash:latest
  links:
    - redis
    - elasticsearch
    - graphite
  env_file: ./env


redis:
  image: redis:latest
  ports:
    - 6379:6379
  env_file: ./env


# data on volume
graphite:
  image: registry.service.dsd.io/opguk/graphite-statsd:latest
  ports:
    - 8003:80
    - 2003:2003
    - 2003:2003/udp
    - 8125:8125/udp
  env_file: ./env


rabbitmq:
  image: registry.service.dsd.io/opguk/rabbitmq:latest
  ports:
    - 5672:5672
  env_file: ./env


sensuserver:
#  build: sensu-server
  image: registry.service.dsd.io/opguk/sensu-server:latest
  links:
    - redis
    - rabbitmq
    - sensuapi
  env_file: ./env


sensuapi:
#  build: sensu-api
  image: registry.service.dsd.io/opguk/sensu-api:latest
  links:
    - redis
    - rabbitmq
  env_file: ./env


sensuclient:
  image: registry.service.dsd.io/opguk/sensu-client:latest
  ports:
    - 3030:3030
  links:
    - redis
    - rabbitmq
    - graphite
  env_file: ./env


uchiwa:
  image: registry.service.dsd.io/opguk/uchiwa:latest
  links:
    - sensuapi
    - sensuserver
  ports:
    - 8004:3000
  env_file: ./env


monitoringproxy:
  image: registry.service.dsd.io/opguk/monitoring-proxy:latest
  links:
    - redis
    - graphite
  environment:
    MONITORING_REDIS_HOST: redis:6379/0
    MONITORING_GRAPHITE: graphite
    MONITORING_NAMESPACE: myapp.prod
  env_file: ./env


# example app feeding logs to the monitoring stack
app:
  image: registry.service.dsd.io/opguk/nginx:latest
  links:
    - monitoringproxy:monitoring
  ports:
    - 8000:80
  env_file: ./env


#example collectd feeder
#collectd:
#  build: collectd
#  links:
#    - monitoringproxy:monitoring
#  env_file: ./env
