#!/bin/sh

name=uchiwa
program=/opt/uchiwa/bin/uchiwa
args="-c /etc/sensu/uchiwa.json -p /opt/uchiwa/src/public"
pidfile="/var/run/$name.pid"

# Run the program!
exec chpst -u uchiwa ${program} ${args}
