#!/bin/sh

name=uchiwa
program=/opt/uchiwa/bin/uchiwa
args="-c /config/config.json -p /opt/uchiwa/src/public"
pidfile="/var/run/$name.pid"

# Run the program!
exec chpst -u uchiwa $program $args >> /var/log/$name.log 2> /var/log/$name.err
