#!/bin/bash
set -e

function abort()
{
	echo "$@"
	exit 1
}

function cleanup()
{
	echo " --> Stopping container"
	docker stop $ID >/dev/null
	docker rm $ID >/dev/null
}

PWD=`pwd`

echo " --> Starting container"
ID=`docker run -d --env-file=../env $NAME:$VERSION /sbin/my_init`
sleep 1


echo " --> Verifying container"
docker ps -q | grep ^${ID:0:12} > /dev/null
if [ $? -ne 0 ]; then
	abort "Unable to verify container IP"
else
  echo " --> Container verified"
fi

trap cleanup EXIT

echo " --> Running tests"

echo " --> Checking Sensu process"
docker exec -it $ID ps -ef | grep sensu-server > /dev/null
if [ $? -ne 0 ]; then
	abort "No Sensu Process running"
else
  echo " --> Sensu is running"
fi
